#!/bin/sh

. /etc/rc.subr

name="node_exporter"
rcvar="${name}_enable"
stop_cmd=""

pidfile="/var/run/${name}.pid"

command="/usr/local/bin/node_exporter"
command_args=""
start_cmd="/usr/sbin/daemon -p $pidfile -f $command $command_args"

load_rc_config $name
run_rc_command "$1"
