#!/bin/sh

. /etc/rc.subr

name="prometheus"
rcvar="${name}_enable"
stop_cmd=""

pidfile="/var/run/${name}.pid"

command="/root/prometheus"
command_args="-config.file=/usr/local/etc/prometheus.yml"
start_cmd="/usr/sbin/daemon -p $pidfile $command $command_args"

load_rc_config $name
run_rc_command "$1"
